package com.MasonCasey;

import com.MasonCasey.student.Student;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.spring.annotation.SpringUI;
import com.vaadin.ui.Button;
import com.vaadin.ui.Notification;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
/*
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
@SpringUI(path="/login")
public class CaseyDesign extends VerticalLayout {
	
	
	
	protected TextField user = new TextField("Username");
	protected TextField tf = new TextField("First Name");
	protected TextField tf2 = new TextField("last Name");
	protected TextField  tf3 = new TextField("College Email");
	protected PasswordField password = new PasswordField("");
	protected Button submitButton;


		

	public CaseyDesign() {
		Design.read(this);

		Student student1 = new Student();	
		
		
		 
	    tf.addValueChangeListener(event -> { //Enter First Name 
	    	String firstName = event.getValue();
	    	student1.setFirst(firstName);
	    });
	    
	    tf2.addValueChangeListener(event -> { //Enter Last name 
	    	String lastName = event.getValue();
	    	student1.setLast(lastName);
	    });
	    
	    tf3.addValueChangeListener(event -> { //Enter email address
	    	String email = event.getValue();
	    	student1.setEmail(email);
	    });
	    
	    submitButton.addClickListener(clickEvent -> { //Adds new users 
	    	try {
				student1.set();
			} catch (Exception e) {
				
				System.out.println(e);
			}
	    	Notification.show("SET");
	    });
		
	}
}
*/